
// Aliases for muscle groups and equipment types
// Map for alternative muscle group names that should match to standard names
export const MUSCLE_GROUP_ALIASES: Record<string, string> = {
  'abdomen': 'Abdômen',
  'abdominal': 'Abdômen',
  'abs': 'Abdômen',
  'abdominais': 'Abdômen',
  'core': 'Abdômen',
  
  'bicep': 'Bíceps',
  'biceps': 'Bíceps',
  'bícep': 'Bíceps',
  'bíceps': 'Bíceps',
  'curl': 'Bíceps',
  'rosca': 'Bíceps',
  'antebraço': 'Bíceps',
  'antebracos': 'Bíceps',
  'antebraços': 'Bíceps',
  'braco': 'Bíceps',
  'braço': 'Bíceps',
  
  'back': 'Costas',
  'superior': 'Costas',
  
  'shoulder': 'Ombros',
  'shoulders': 'Ombros',
  'ombro': 'Ombros',
  'ombros': 'Ombros',
  'deltoides': 'Ombros',
  
  'chest': 'Peito',
  'peitoral': 'Peito',
  
  'legs': 'Pernas',
  'pernas': 'Pernas',
  'leg': 'Pernas',
  'coxa': 'Pernas',
  'coxas': 'Pernas',
  'quads': 'Pernas',
  'quadríceps': 'Pernas',
  
  'tricep': 'Tríceps',
  'triceps': 'Tríceps',
  'trícep': 'Tríceps',
  'extensão': 'Tríceps',
  'extensao': 'Tríceps',
  'pushdown': 'Tríceps',
  'francês': 'Tríceps',
  'frances': 'Tríceps',
  'mergulho': 'Tríceps',
  'paralela': 'Tríceps',
  'testa': 'Tríceps',
  'coice': 'Tríceps',
  'corda': 'Tríceps',
  'banco': 'Tríceps',
  'diamante': 'Tríceps',
  
  'cardio': 'Cardio',
  'aerobic': 'Cardio',
  'aerobico': 'Cardio',
  'aeróbico': 'Cardio',
  'endurance': 'Cardio',
  'resistencia': 'Cardio',
  'resistência': 'Cardio',
  'corrida': 'Cardio',
  'correr': 'Cardio',
  'esteira': 'Cardio',
  'ciclismo': 'Cardio',
  'bike': 'Cardio',
  'bicicleta': 'Cardio',
  'remo': 'Cardio',
  'pular': 'Cardio',
  'jump': 'Cardio',
  'rope': 'Cardio',
  'elliptical': 'Cardio',
  'eliptico': 'Cardio',
  'elíptico': 'Cardio',
  'spinning': 'Cardio',
  'aerobica': 'Cardio',
  'aeróbica': 'Cardio',
  
  'sport': 'Esportes',
  'esporte': 'Esportes',
  'sports': 'Esportes',
  'futebol': 'Esportes',
  'soccer': 'Esportes',
  'football': 'Esportes',
  'basquete': 'Esportes',
  'basketball': 'Esportes',
  'volei': 'Esportes',
  'vôlei': 'Esportes',
  'volley': 'Esportes',
  'volleyball': 'Esportes',
  'tenis': 'Esportes',
  'tênis': 'Esportes',
  'tennis': 'Esportes',
  'natação': 'Esportes',
  'natacao': 'Esportes',
  'swimming': 'Esportes',
  'handball': 'Esportes',
  'handebol': 'Esportes',
  'boxe': 'Esportes',
  'boxing': 'Esportes',
  'luta': 'Esportes',
  'martial': 'Esportes',
  'golf': 'Esportes',
  'golfe': 'Esportes',
  'rugby': 'Esportes',
  'badminton': 'Esportes',
  'squash': 'Esportes'
};

// Map for alternative equipment types that should match to standard names
export const EQUIPMENT_TYPE_ALIASES: Record<string, string> = {
  'bodyweight': 'Nenhum',
  'corpo': 'Nenhum',
  'none': 'Nenhum',
  'sem equipamento': 'Nenhum',
  'barbell': 'Barra',
  'dumbbell': 'Halter',
  'dumbbells': 'Halter',
  'halteres': 'Halter',
  'machine': 'Máquina',
  'maquina': 'Máquina',
  'máquina': 'Máquina',
  'kettle': 'Kettlebell',
  'kb': 'Kettlebell',
  'bench': 'Banco',
  'band': 'Elástico',
  'bands': 'Elástico',
  'elastic': 'Elástico',
  'elastico': 'Elástico',
  'resistance band': 'Elástico',
  'suspension': 'TRX',
  'cable': 'Cabo',
  'pulley': 'Cabo',
  'other': 'Outro',
  'treadmill': 'Barra de Cardio',
  'esteira': 'Barra de Cardio',
  'bike': 'Barra de Cardio',
  'bicycle': 'Barra de Cardio',
  'bicicleta': 'Barra de Cardio',
  'ergometrica': 'Barra de Cardio',
  'ergométrica': 'Barra de Cardio',
  'elliptical': 'Barra de Cardio',
  'eliptico': 'Barra de Cardio',
  'elíptico': 'Barra de Cardio',
  'rower': 'Barra de Cardio',
  'remo': 'Barra de Cardio',
  'stair': 'Barra de Cardio',
  'escada': 'Barra de Cardio',
  'rope': 'Barra de Cardio',
  'corda': 'Barra de Cardio',
  'ball': 'Equipamento de Esportes',
  'bola': 'Equipamento de Esportes',
  'racket': 'Equipamento de Esportes',
  'raquete': 'Equipamento de Esportes',
  'gloves': 'Equipamento de Esportes',
  'luvas': 'Equipamento de Esportes',
  'net': 'Equipamento de Esportes',
  'rede': 'Equipamento de Esportes',
  'goal': 'Equipamento de Esportes',
  'gol': 'Equipamento de Esportes',
  'hoop': 'Equipamento de Esportes',
  'cesta': 'Equipamento de Esportes'
};
