
// Exercise categorization map for precise category mapping
export const EXERCISE_CATEGORY_MAP: Record<string, string> = {
  'corrida': 'Cardio',
  'correr': 'Cardio',
  'esteira': 'Cardio',
  'ciclismo': 'Cardio',
  'bicicleta': 'Cardio',
  'bike': 'Cardio',
  'remo': 'Cardio',
  'pular corda': 'Cardio',
  'jump rope': 'Cardio',
  'jumping': 'Cardio',
  'elíptico': 'Cardio',
  'eliptico': 'Cardio',
  'elliptical': 'Cardio',
  'spinning': 'Cardio',
  'caminhada': 'Cardio',
  'walk': 'Cardio',
  'marcha': 'Cardio',
  'cardio': 'Cardio',
  'aeróbico': 'Cardio',
  'aerobico': 'Cardio',
  'step': 'Cardio',
  'escada': 'Cardio',
  'burpee': 'Cardio',
  'mountain climber': 'Cardio',
  'escalador': 'Cardio',
  'hiit': 'Cardio',
  'intervalo': 'Cardio',
  'circuit': 'Cardio',
  'circuito': 'Cardio',
  'tabata': 'Cardio',
  
  'futebol': 'Esportes',
  'soccer': 'Esportes',
  'football': 'Esportes',
  'basquete': 'Esportes',
  'basketball': 'Esportes',
  'vôlei': 'Esportes',
  'volei': 'Esportes',
  'volleyball': 'Esportes',
  'tênis': 'Esportes',
  'tenis': 'Esportes',
  'tennis': 'Esportes',
  'natação': 'Esportes',
  'natacao': 'Esportes',
  'swimming': 'Esportes',
  'handball': 'Esportes',
  'handebol': 'Esportes',
  'boxe': 'Esportes',
  'boxing': 'Esportes',
  'luta': 'Esportes',
  'martial': 'Esportes',
  'golf': 'Esportes',
  'golfe': 'Esportes',
  'rugby': 'Esportes',
  'badminton': 'Esportes',
  'squash': 'Esportes',
  'beisebol': 'Esportes',
  'baseball': 'Esportes',
  'esgrima': 'Esportes',
  'fencing': 'Esportes',
  'ginástica': 'Esportes',
  'ginastica': 'Esportes',
  'hockey': 'Esportes',
  'hóquei': 'Esportes',
  'hoquei': 'Esportes',
  'judo': 'Esportes',
  'judô': 'Esportes',
  'karate': 'Esportes',
  'karatê': 'Esportes',
  'polo': 'Esportes',
  'skating': 'Esportes',
  'patinação': 'Esportes',
  'patinacao': 'Esportes',
  'surf': 'Esportes',
  'wrestling': 'Esportes',
  'yoga': 'Esportes',
  'pilates': 'Esportes',
  'taekwondo': 'Esportes',
  'artes marciais': 'Esportes'
};
