
-- Update achievement seed data with complete set
INSERT INTO public.achievements (
  id,
  name,
  description,
  category,
  rank,
  points,
  xp_reward,
  icon_name,
  requirements,
  string_id
) VALUES
  ('first-workout', 'Primeiro Treino', 'Complete seu primeiro treino', 'workout', 'E', 1, 50, 'dumbbell', '{"workouts_count": 1}', 'first-workout'),
  ('weekly-workouts', 'Trio na Semana', 'Complete 3 treinos em uma semana', 'workout', 'E', 1, 75, 'calendar', '{"weekly_workouts": 3}', 'weekly-three'),
  ('streak-3', 'Trinca Poderosa', 'Treine por 3 dias consecutivos', 'streak', 'E', 1, 75, 'flame', '{"streak_days": 3}', 'first-streak'),
  ('pr-first', 'Quebra-Recorde', 'Estabeleça seu primeiro recorde pessoal', 'record', 'D', 3, 100, 'trending-up', '{"pr_count": 1}', 'first-pr'),
  ('level-5', 'Herói em Ascensão', 'Atinja o nível 5', 'level', 'E', 1, 50, 'arrow-up', '{"level": 5}', 'level-five'),
  ('first-guild', 'Primeira Guilda', 'Junte-se à sua primeira guilda', 'guild', 'E', 1, 50, 'users', '{"guild_count": 1}', 'first-guild'),
  ('manual-first', 'Esporte de Primeira', 'Registre seu primeiro treino manual', 'manual', 'E', 1, 50, 'camera', '{"manual_count": 1}', 'first-manual'),
  ('xp-1000', 'Primeiro Milhar', 'Acumule 1.000 XP', 'xp', 'C', 3, 100, 'trending-up', '{"total_xp": 1000}', 'xp-milestone-1000'),
  ('total-7', 'Embalo Fitness', 'Complete 7 treinos no total', 'workout', 'E', 1, 75, 'activity', '{"workouts_count": 7}', 'total-7'),
  ('total-10', 'Dedicação Semanal', 'Complete 10 treinos no total', 'workout', 'D', 2, 100, 'activity', '{"workouts_count": 10}', 'total-10'),
  ('diario-do-suor', 'Diário do Suor', 'Complete 3 treinos manuais', 'manual', 'E', 1, 75, 'book', '{"manual_count": 3}', 'diario-do-suor'),
  ('pr-5', 'Recordista Novato', 'Estabeleça 5 recordes pessoais', 'record', 'D', 3, 125, 'award', '{"pr_count": 5}', 'pr-5'),
  ('streak-7', 'Semana Impecável', 'Mantenha uma sequência de 7 dias', 'streak', 'D', 3, 125, 'flame', '{"streak_days": 7}', 'streak-7'),
  ('streak-14', 'Duas Semanas Perfeitas', 'Mantenha uma sequência de 14 dias', 'streak', 'C', 5, 150, 'flame', '{"streak_days": 14}', 'streak-14'),
  ('streak-30', 'Mês Disciplinado', 'Mantenha uma sequência de 30 dias', 'streak', 'B', 8, 200, 'flame', '{"streak_days": 30}', 'streak-30'),
  ('streak-60', 'Bimestre Poderoso', 'Mantenha uma sequência de 60 dias', 'streak', 'A', 10, 300, 'flame', '{"streak_days": 60}', 'streak-60'),
  ('streak-100', 'Centena Imparável', 'Mantenha uma sequência de 100 dias', 'streak', 'S', 15, 500, 'flame', '{"streak_days": 100}', 'streak-100'),
  ('streak-365', 'Ano Lendário', 'Mantenha uma sequência de 365 dias', 'streak', 'S', 25, 1000, 'flame', '{"streak_days": 365}', 'streak-365'),
  ('multiple-guilds', 'Amigo de Guilda', 'Junte-se a 3 ou mais guildas', 'guild', 'D', 3, 125, 'users', '{"guild_count": 3}', 'multiple-guilds'),
  ('manual-5', 'Aventureiro Fitness', 'Complete 5 treinos manuais', 'manual', 'D', 2, 100, 'map', '{"manual_count": 5}', 'manual-5'),
  ('manual-10', 'Explorador do Movimento', 'Complete 10 treinos manuais', 'manual', 'C', 4, 150, 'compass', '{"manual_count": 10}', 'manual-10'),
  ('variety-3', 'Aventuras Fitness', 'Registre 3 tipos diferentes de treinos', 'variety', 'D', 3, 125, 'layers', '{"activity_types": 3}', 'variety-3'),
  ('variety-5', 'Atleta Versátil', 'Registre 5 tipos diferentes de treinos', 'variety', 'C', 5, 200, 'layers', '{"activity_types": 5}', 'variety-5'),
  ('exercise-variety-3', 'Primeiros Movimentos', 'Complete 3 exercícios diferentes', 'exercise_variety', 'D', 2, 100, 'grid', '{"exercise_types": 3}', 'exercise-variety-3'),
  ('exercise-variety-5', 'Repertório Crescente', 'Complete 5 exercícios diferentes', 'exercise_variety', 'C', 4, 150, 'grid', '{"exercise_types": 5}', 'exercise-variety-5'),
  ('exercise-variety-10', 'Arsenal Completo', 'Complete 10 exercícios diferentes', 'exercise_variety', 'B', 6, 200, 'grid', '{"exercise_types": 10}', 'exercise-variety-10'),
  ('total-25', 'Maratona Mensal', 'Complete 25 treinos no total', 'workout', 'C', 5, 150, 'activity', '{"workouts_count": 25}', 'total-25'),
  ('total-50', 'Meio Centenário', 'Complete 50 treinos no total', 'workout', 'B', 8, 250, 'activity', '{"workouts_count": 50}', 'total-50'),
  ('total-100', 'Centenário Fitness', 'Complete 100 treinos no total', 'workout', 'A', 10, 350, 'activity', '{"workouts_count": 100}', 'total-100'),
  ('total-200', 'Bicentenário da Força', 'Complete 200 treinos no total', 'workout', 'S', 15, 500, 'activity', '{"workouts_count": 200}', 'total-200'),
  ('pr-10', 'Recordista Experiente', 'Estabeleça 10 recordes pessoais', 'record', 'C', 5, 200, 'award', '{"pr_count": 10}', 'pr-10'),
  ('pr-25', 'Quebrador de Limites', 'Estabeleça 25 recordes pessoais', 'record', 'B', 8, 300, 'award', '{"pr_count": 25}', 'pr-25'),
  ('pr-50', 'Mestre dos Recordes', 'Estabeleça 50 recordes pessoais', 'record', 'A', 12, 500, 'award', '{"pr_count": 50}', 'pr-50'),
  ('xp-5000', 'Cinco Milhares', 'Acumule 5.000 XP', 'xp', 'B', 5, 200, 'trending-up', '{"total_xp": 5000}', 'xp-5000'),
  ('xp-10000', 'Dez Milhares', 'Acumule 10.000 XP', 'xp', 'A', 8, 300, 'trending-up', '{"total_xp": 10000}', 'xp-10000'),
  ('xp-50000', 'Cinquenta Milhares', 'Acumule 50.000 XP', 'xp', 'S', 12, 500, 'trending-up', '{"total_xp": 50000}', 'xp-50000'),
  ('xp-100000', 'Cem Milhares', 'Acumule 100.000 XP', 'xp', 'S', 15, 1000, 'trending-up', '{"total_xp": 100000}', 'xp-100000')
ON CONFLICT (id) DO 
  UPDATE SET 
    name = EXCLUDED.name,
    description = EXCLUDED.description,
    category = EXCLUDED.category,
    rank = EXCLUDED.rank,
    points = EXCLUDED.points,
    xp_reward = EXCLUDED.xp_reward,
    requirements = EXCLUDED.requirements,
    string_id = EXCLUDED.string_id;
