// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://frzgnszosqvcgycjtntz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZyemduc3pvc3F2Y2d5Y2p0bnR6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQwNTAxNDAsImV4cCI6MjA1OTYyNjE0MH0.aumHzbWPsSB2rYCsyjflPTHHj3bB9a6CZqDueknNkRo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);